=pod

=head1 Jive

Jive API documentation.

=head2 Style guide

L<Style Guide>

=head2 Package jive

L<jive.Applet|jive::Applet>

L<jive.AppletManager|jive::AppletManager>

L<jive.AppletMeta|jive::AppletMeta>

L<jive.Iconbar|jive::Iconbar>

L<jive.JiveMain|jive::JiveMain>


=head2 Package jive.net

L<jive.net.HttpPool|jive::net::HttpPool>

L<jive.net.NetworkThread|jive::net::NetworkThread>

L<jive.net.RequestHttp|jive::net::RequestHttp>

L<jive.net.RequestJsonRpc|jive::net::RequestJsonRpc>

L<jive.net.SocketHttp|jive::net::SocketHttp>

L<jive.net.SocketHttpQueue|jive::net::SocketHttpQueue>

L<jive.net.Socket|jive::net::Socket>

L<jive.net.SocketTcp|jive::net::SocketTcp>

L<jive.net.SocketUdpBcast|jive::net::SocketUdpBcast>


=head2 Package jive.slim

L<jive.slim.Player|jive::slim::Player>

L<jive.slim.RequestsCli|jive::slim::RequestsCli>

L<jive.slim.SlimServer|jive::slim::SlimServer>

L<jive.slim.SlimServers|jive::slim::SlimServers>


=head2 Package jive.ui

L<jive.ui.Audio|jive::ui::Audio>

L<jive.ui.Checkbox|jive::ui::Checkbox>

L<jive.ui.Choice|jive::ui::Choice>

L<jive.ui.Event|jive::ui::Event>

L<jive.ui.Font|jive::ui::Font>

L<jive.ui.Framework|jive::ui::Framework>

L<jive.ui.Icon|jive::ui::Icon>

L<jive.ui.Label|jive::ui::Label>

L<jive.ui.Menu|jive::ui::Menu>

L<jive.ui.Popup|jive::ui::Popup>

L<jive.ui.RadioButton|jive::ui::RadioButton>

L<jive.ui.RadioGroup|jive::ui::RadioGroup>

L<jive.ui.SimpleMenu|jive::ui::SimpleMenu>

L<jive.ui.Surface|jive::ui::Surface>

L<jive.ui.Textarea|jive::ui::Textarea>

L<jive.ui.Timer|jive::ui::Timer>

L<jive.ui.Widget|jive::ui::Widget>

L<jive.ui.Window|jive::ui::Window>


=head2 Package jive.utils

L<jive.utils.autotable|jive::utils::autotable>

L<jive.utils.debug|jive::utils::debug>

L<jive.utils.jsonfilters|jive::utils::jsonfilters>

L<jive.utils.log|jive::utils::log>

L<jive.utils.queue|jive::utils::queue>

L<jive.utils.strings|jive::utils::strings>

L<jive.utils.table|jive::utils::table>


=head2 Applets

L<applets.Bounce.BounceApplet|applets::Bounce::BounceApplet>

L<applets.Flickr.FlickrApplet|applets::Flickr::FlickrApplet>

L<applets.KeyLock.KeyLockApplet|applets::KeyLock::KeyLockApplet>

L<applets.LogSettings.LogSettingsApplet|applets::LogSettings::LogSettingsApplet>

L<applets.Quit.QuitApplet|applets::Quit::QuitApplet>

L<applets.ScreenSavers.ScreenSaversApplet|applets::ScreenSavers::ScreenSaversApplet>

L<applets.SlimBrowser.SlimBrowserApplet|applets::SlimBrowser::SlimBrowserApplet>

L<applets.SlimDiscovery.SlimDiscoveryApplet|applets::SlimDiscovery::SlimDiscoveryApplet>

L<applets.Test.TestApplet|applets::Test::TestApplet>

