include config

COMMON_OBJS= src/clocks.o src/core_profiler.o src/function_meter.o src/stack.o
LUA50_OBJS= src/lua50_profiler.o


$(LUA_50_OUTPUT): $(COMMON_OBJS) $(LUA50_OBJS)
	$(LD) -Bshareable -o $(LUA_50_OUTPUT) $(COMMON_OBJS) $(LUA50_OBJS)


clean:
	rm -f $(LUA_50_OUTPUT) src/*.o

install: $(LUA_50_OUTPUT)
	install -m 0755 $(LUA_50_OUTPUT) $(PREFIX)/lib/lua/5.1
	install -m 0755 src/analyzer/lprof $(PREFIX)/bin

