
APPLETS=${PREFIX}/share/jive/applets

all:
	install -D share/applets/Bounce/BounceApplet.lua ${APPLETS}/Bounce/BounceApplet.lua
	install -D share/applets/Bounce/BounceMeta.lua ${APPLETS}/Bounce/BounceMeta.lua
	install -D share/applets/Bounce/squeezebox.png ${APPLETS}/Bounce/squeezebox.png
	install -D share/applets/Bounce/strings.txt ${APPLETS}/Bounce/strings.txt
	install -D share/applets/Quit/QuitMeta.lua ${APPLETS}/Quit/QuitMeta.lua
	install -D share/applets/Quit/strings.txt ${APPLETS}/Quit/strings.txt
	install -D share/applets/SetupWelcome/settings.lua ${APPLETS}/SetupWelcome/settings.lua
	install -D share/applets/SetupWelcome/SetupWelcomeApplet.lua ${APPLETS}/SetupWelcome/SetupWelcomeApplet.lua
	install -D share/applets/SetupWelcome/SetupWelcomeMeta.lua ${APPLETS}/SetupWelcome/SetupWelcomeMeta.lua
	install -D share/applets/SetupWelcome/strings.txt ${APPLETS}/SetupWelcome/strings.txt
	install -D share/applets/Test/strings.txt ${APPLETS}/Test/strings.txt
	install -D share/applets/Test/TestApplet.lua ${APPLETS}/Test/TestApplet.lua
	install -D share/applets/Test/test.gif ${APPLETS}/Test/test.gif
	install -D share/applets/Test/test.jpg ${APPLETS}/Test/test.jpg
	install -D share/applets/Test/TestMeta.lua ${APPLETS}/Test/TestMeta.lua
	install -D share/applets/Test/test.png ${APPLETS}/Test/test.png
	install -D share/applets/Test/test.txt ${APPLETS}/Test/test.txt
