
APPLETS=${PREFIX}/share/jive/applets

all:
	install -d share/applets/Quit ${APPLETS}/Quit
	install share/applets/Quit/QuitMeta.lua ${APPLETS}/Quit/QuitMeta.lua
	install share/applets/Quit/strings.txt ${APPLETS}/Quit/strings.txt
	install -d share/applets/SetupWelcome ${APPLETS}/SetupWelcome
	install share/applets/SetupWelcome/SetupWelcomeApplet.lua ${APPLETS}/SetupWelcome/SetupWelcomeApplet.lua
	install share/applets/SetupWelcome/SetupWelcomeMeta.lua ${APPLETS}/SetupWelcome/SetupWelcomeMeta.lua
	install share/applets/SetupWelcome/strings.txt ${APPLETS}/SetupWelcome/strings.txt
	install -d share/applets/TestDecode ${APPLETS}/TestDecode
	install share/applets/TestDecode/TestDecodeApplet.lua ${APPLETS}/TestDecode/TestDecodeApplet.lua
	install share/applets/TestDecode/TestDecodeMeta.lua ${APPLETS}/TestDecode/TestDecodeMeta.lua
	install -d share/applets/DesktopJive ${APPLETS}/DesktopJive
	install share/applets/DesktopJive/DesktopJiveMeta.lua ${APPLETS}/DesktopJive/DesktopJiveMeta.lua
