
APPLETS=${PREFIX}/share/jive/applets

all:
	install -d share/applets/Bounce ${APPLETS}/Bounce
	install share/applets/Bounce/BounceApplet.lua ${APPLETS}/Bounce/BounceApplet.lua
	install share/applets/Bounce/BounceMeta.lua ${APPLETS}/Bounce/BounceMeta.lua
	install share/applets/Bounce/squeezebox.png ${APPLETS}/Bounce/squeezebox.png
	install share/applets/Bounce/strings.txt ${APPLETS}/Bounce/strings.txt
	install -d share/applets/Test ${APPLETS}/Test
	install share/applets/Test/strings.txt ${APPLETS}/Test/strings.txt
	install share/applets/Test/TestApplet.lua ${APPLETS}/Test/TestApplet.lua
	install share/applets/Test/test.gif ${APPLETS}/Test/test.gif
	install share/applets/Test/test.jpg ${APPLETS}/Test/test.jpg
	install share/applets/Test/TestMeta.lua ${APPLETS}/Test/TestMeta.lua
	install share/applets/Test/test.png ${APPLETS}/Test/test.png
	install share/applets/Test/test.txt ${APPLETS}/Test/test.txt
